package com.imaec.hiseoul

const val ACTION_GET_LIST = "ACTION_GET_LIST"
const val IS_NOT_REGISTERD = "SERVICE KEY IS NOT REGISTERED ERROR."
const val LIMITED_REQUEST = "LIMITED NUMBER OF SERVICE REQUESTS EXCEEDS ERROR."